// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDsvBH_iEGXeujU5UpBRox3mP1ne6T7O4',
    appId: '1:1050664475960:web:48964cb2659be1fe5c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    authDomain: 'clb-dnsg-a9b44.firebaseapp.com',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    measurementId: 'G-BTHFVVK012',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXTJpXmzcgYq1Aqlz969Q2Ys5hc8enpU',
    appId: '1:1050664475960:android:9878bc1f45f0a2d55c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUR0i_4RKEFVZF2lEryvmuYVFXs4287Sk',
    appId: '1:1050664475960:ios:538ad943a15e11255c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    androidClientId: '1050664475960-tp7n1cu9erc5au2v1sei4q001t08la1o.apps.googleusercontent.com',
    iosBundleId: 'com.webest.clbdoanhnhansg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUR0i_4RKEFVZF2lEryvmuYVFXs4287Sk',
    appId: '1:1050664475960:ios:538ad943a15e11255c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    androidClientId: '1050664475960-tp7n1cu9erc5au2v1sei4q001t08la1o.apps.googleusercontent.com',
    iosBundleId: 'com.webest.clbdoanhnhansg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDsvBH_iEGXeujU5UpBRox3mP1ne6T7O4',
    appId: '1:1050664475960:web:7c35c92b62d274735c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    authDomain: 'clb-dnsg-a9b44.firebaseapp.com',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    measurementId: 'G-5XRWRLW1NL',
  );
}
