// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLCcO9T0Pc9KuEsRMnuDMoi-Ct9Mn8Gk',
    appId: '1:1050664475960:web:d3b2d3ea1fb04be65c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    authDomain: 'clb-dnsg-a9b44.firebaseapp.com',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    measurementId: 'G-PWR7DEC0K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXTJpXmzcgYq1Aqlz969Q2Ys5hc8enpU',
    appId: '1:1050664475960:android:6d295be8cef9350c5c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUR0i_4RKEFVZF2lEryvmuYVFXs4287Sk',
    appId: '1:1050664475960:ios:5a0aa49daa2c93c15c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUR0i_4RKEFVZF2lEryvmuYVFXs4287Sk',
    appId: '1:1050664475960:ios:5a0aa49daa2c93c15c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZLCcO9T0Pc9KuEsRMnuDMoi-Ct9Mn8Gk',
    appId: '1:1050664475960:web:09ab4cc0724e24685c75cd',
    messagingSenderId: '1050664475960',
    projectId: 'clb-dnsg-a9b44',
    authDomain: 'clb-dnsg-a9b44.firebaseapp.com',
    storageBucket: 'clb-dnsg-a9b44.firebasestorage.app',
    measurementId: 'G-W8K5781631',
  );
}
